sudo: false
language: node_js
node_js: node

env:
  global:
    - MONGODB=3.2.13
  matrix:
    - PACKAGE_MANAGER=yarn
    - PACKAGE_MANAGER=npm

before_install:
  - npm install -g greenkeeper-lockfile@1

install:
  - if [ "$PACKAGE_MANAGER" == "npm" ]; then npm install; else yarn; fi

before_script:
  - greenkeeper-lockfile-update
  - npm prune

script:
  - npm run build
  - npm run lint
  - npm run duplication -- --limit=0.01

jobs:
  include:
    - stage: publish
      if: env(PACKAGE_MANAGER) = npm
      script:
        - npm run semantic-release
        - greenkeeper-lockfile-upload