sudo: false
language: node_js
node_js: node

cache:
  - yarn: true

before_install:
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run build
  - npm run lint
  - npm run duplication -- --limit=0.01

after_succes:
  - npm run semantic-release
  - greenkeeper-lockfile-upload